# Pandas

In [1]:
import pandas as pd
import numpy as np

## Dataframe using array

In [2]:
data_frame_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
pd.DataFrame(data_frame_array,index=["row_0","row_1","row_2"], columns=['col_1', 'col_2', 'col_3'])

       col_1  col_2  col_3
row_0      1      2      3
row_1      4      5      6
row_2      7      8      9

## Dataframe using list

In [42]:
data_frame_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [46]:
pd.DataFrame(data_frame_list,index=["row_0","row_1","row_2"], columns=['col_1', 'col_2', 'col_3'])

       col_1  col_2  col_3
row_0      1      2      3
row_1      4      5      6
row_2      7      8      9

## Dataframe from dictionary

In [40]:
south_states=["Telangana","Kerala","Tamilanadu","Karnataka","Andhra Pradesh"]
population = [39613493, 29730311, 21944577, 19299981,9299981]

In [30]:
status_dictionary={"stateName": south_states, "population": population}

In [14]:
pd.DataFrame(status_dictionary)

        stateName  population
0       Telangana    39613493
1          Kerala    29730311
2      Tamilanadu    21944577
3       Karnataka    19299981
4  Andhra Pradesh     9299981

## Dataframe from CSV

In [2]:
data_frame_csv = pd.read_csv("StudentsPerformance.csv")

In [29]:
data_frame_csv

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,min_mix_score
0,female,group B,bachelor's degree,standard,none,72,72,74,80
1,female,group C,some college,standard,completed,69,90,88,81
2,female,group B,master's degree,standard,none,90,95,93,84
3,male,group A,associate's degree,free/reduced,none,47,57,44,86
4,male,group C,some college,standard,none,76,78,75,83
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,80
996,male,group C,high school,free/reduced,none,62,55,55,84
997,female,group C,high school,free/reduced,completed,59,71,65,86
998,female,group D,some college,standard,completed,68,78,77,84
999,female,group D,some college,free/reduced,none,77,86,86,86

### Display first 5 rows

In [6]:
data_frame_csv.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,avg_score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667
1,female,group C,some college,standard,completed,69,90,88,82.333333
2,female,group B,master's degree,standard,none,90,95,93,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333
4,male,group C,some college,standard,none,76,78,75,76.333333

### Display last 5 rows

In [23]:
data_frame_csv.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

### Display first N rows

In [24]:
data_frame_csv.head(8)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39

### Display last N rows

In [25]:
data_frame_csv.tail(8)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

### Display shape of file(rows,columns)

In [26]:
data_frame_csv.shape

(1000, 8)

### Display all

In [45]:
pd.set_option('display.max_rows', 10)

In [47]:
data_frame_csv

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

### Getting Index

In [5]:
data_frame_csv.index

RangeIndex(start=0, stop=1000, step=1)

### Getting columns

In [6]:
data_frame_csv.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

### Getting Datatypes

In [8]:
data_frame_csv.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

### Info

In [10]:
data_frame_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

### Description

In [11]:
data_frame_csv.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### Length of dataframe

In [12]:
len(data_frame_csv)

1000

### Max index

In [13]:
max(data_frame_csv.index)

999

### Min index

In [14]:
min(data_frame_csv.index)

0

### Dataframe type

In [15]:
type(data_frame_csv)

pandas.core.frame.DataFrame

### Rounding off value

In [16]:
round(data_frame_csv,2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

### Select one column

In [17]:
data_frame_csv["gender"]

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

### Type of column

In [6]:
type(data_frame_csv["gender"])

pandas.core.series.Series

In [7]:
data_frame_csv.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [8]:
data_frame_csv["math score"]

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

### Selecting multiple columns

In [9]:
data_frame_csv[["gender", "math score"]]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

### Selecting multiple columns type

In [10]:
type(data_frame_csv[["gender", "math score"]])

pandas.core.frame.DataFrame

### Multiple columns

In [11]:
data_frame_csv[["gender", "math score","parental level of education"]]

     gender  math score parental level of education
0    female          72           bachelor's degree
1    female          69                some college
2    female          90             master's degree
3      male          47          associate's degree
4      male          76                some college
..      ...         ...                         ...
995  female          88             master's degree
996    male          62                 high school
997  female          59                 high school
998  female          68                some college
999  female          77                some college

[1000 rows x 3 columns]

### Adding new column

In [15]:
data_frame_csv["min_mix_score"] = 8

In [16]:
data_frame_csv

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,min_mix_score
0,female,group B,bachelor's degree,standard,none,72,72,74,8
1,female,group C,some college,standard,completed,69,90,88,8
2,female,group B,master's degree,standard,none,90,95,93,8
3,male,group A,associate's degree,free/reduced,none,47,57,44,8
4,male,group C,some college,standard,none,76,78,75,8
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,8
996,male,group C,high school,free/reduced,none,62,55,55,8
997,female,group C,high school,free/reduced,completed,59,71,65,8
998,female,group D,some college,standard,completed,68,78,77,8
999,female,group D,some college,free/reduced,none,77,86,86,8

In [20]:
min_mix_score = np.arange(1,1001)

In [21]:
data_frame_csv["min_mix_score"] = min_mix_score

In [23]:
data_frame_csv["min_mix_score"]

0         1
1         2
2         3
3         4
4         5
       ...
995     996
996     997
997     998
998     999
999    1000
Name: min_mix_score, Length: 1000, dtype: int64

In [30]:
min_mix_score = np.random.randint(80,89, size=1000)
data_frame_csv["min_mix_score"] = min_mix_score

In [27]:
data_frame_csv["min_mix_score"]

0      91
1      98
2      94
3      95
4      77
       ..
995    84
996    83
997    85
998    77
999    85
Name: min_mix_score, Length: 1000, dtype: int32

### 2nd way to add new column using assign()

In [4]:
score_one = np.random.randint(80,89, size=1000)
score_two = np.random.randint(80,89, size=1000)

In [7]:
series_one = pd.Series(score_one, index=np.arange(0,1000))
series_two = pd.Series(score_two, index=np.arange(0,1000))

0      84
1      81
2      83
3      83
4      83
       ..
995    83
996    85
997    86
998    86
999    87
Length: 1000, dtype: int32
0      82
1      82
2      81
3      82
4      83
       ..
995    85
996    81
997    81
998    86
999    84
Length: 1000, dtype: int32

In [8]:
data_frame_csv.assign(score_one=series_one, score_two=series_two)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score_one,score_two
0,female,group B,bachelor's degree,standard,none,72,72,74,84,82
1,female,group C,some college,standard,completed,69,90,88,81,82
2,female,group B,master's degree,standard,none,90,95,93,83,81
3,male,group A,associate's degree,free/reduced,none,47,57,44,83,82
4,male,group C,some college,standard,none,76,78,75,83,83
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,83,85
996,male,group C,high school,free/reduced,none,62,55,55,85,81
997,female,group C,high school,free/reduced,completed,59,71,65,86,81
998,female,group D,some college,standard,completed,68,78,77,86,86
999,female,group D,some college,free/reduced,none,77,86,86,87,84

### 3rd way to add new column using insert()

In [9]:
data_frame_csv.insert(1, "score_three", series_one)

In [12]:
data_frame_csv

,gender,score_three,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,84,group B,bachelor's degree,standard,none,72,72,74
1,female,81,group C,some college,standard,completed,69,90,88
2,female,83,group B,master's degree,standard,none,90,95,93
3,male,83,group A,associate's degree,free/reduced,none,47,57,44
4,male,83,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,83,group E,master's degree,standard,completed,88,99,95
996,male,85,group C,high school,free/reduced,none,62,55,55
997,female,86,group C,high school,free/reduced,completed,59,71,65
998,female,86,group D,some college,standard,completed,68,78,77
999,female,87,group D,some college,free/reduced,none,77,86,86

### Math operations on columns

In [13]:
data_frame_csv["score_three"].sum()

np.int64(66089)

In [14]:
data_frame_csv["score_three"].mean()

np.float64(66.089)

In [15]:
data_frame_csv["score_three"].count()

np.int64(1000)

In [17]:
data_frame_csv["score_three"].std()

np.float64(2.6166288897638403)

In [18]:
data_frame_csv["score_three"].min()

np.int32(80)

In [19]:
data_frame_csv["score_three"].max()

np.int32(88)

In [20]:
data_frame_csv.describe()

       score_three  math score  reading score  writing score
count  1000.000000  1000.00000    1000.000000    1000.000000
mean     83.890000    66.08900      69.169000      68.054000
std       2.616629    15.16308      14.600192      15.195657
min      80.000000     0.00000      17.000000      10.000000
25%      82.000000    57.00000      59.000000      57.750000
50%      84.000000    66.00000      70.000000      69.000000
75%      86.000000    77.00000      79.000000      79.000000
max      88.000000   100.00000     100.000000     100.000000

### Operations on rows

In [21]:
data_frame_csv["math score"]+data_frame_csv["reading score"]+data_frame_csv["writing score"]

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [5]:
data_frame_csv["avg_score"] = (data_frame_csv["math score"] + data_frame_csv["reading score"] + data_frame_csv["writing score"]) / 3

In [7]:
data_frame_csv["avg_score"]

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Name: avg_score, Length: 1000, dtype: float64

### Count values

In [8]:
data_frame_csv["gender"].count()

np.int64(1000)

In [9]:
data_frame_csv["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [10]:
data_frame_csv["gender"].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [11]:
data_frame_csv["parental level of education"].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [12]:
data_frame_csv["parental level of education"].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

##  Sorting

In [13]:
data_frame_csv["math score"].sort_values(ascending=False)

451    100
458    100
962    100
149    100
623    100
      ...
145     22
787     19
17      18
980      8
59       0
Name: math score, Length: 1000, dtype: int64

In [14]:
data_frame_csv.sort_values(ascending=False, by="math score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,avg_score
451,female,group E,some college,standard,none,100,92,97,96.333333
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
623,male,group A,some college,standard,completed,100,96,86,94.000000
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [15]:
data_frame_csv.sort_values(ascending=True, by="math score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,avg_score
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
787,female,group B,some college,standard,none,19,38,32,29.666667
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
...,...,...,...,...,...,...,...,...,...
623,male,group A,some college,standard,completed,100,96,86,94.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000

In [16]:
data_frame_csv.sort_values(ascending=True, by=["math score", "reading score","writing score"])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,avg_score
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
787,female,group B,some college,standard,none,19,38,32,29.666667
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
...,...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99,98.666667
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000